version: '2'
services: 
    ap:
        build: ./docker/ap
        ports:
            - "8000:80"
            - "9100-9110:9100-9110"
        volumes:
            - ./app:/var/www/html
            - ./docker/ap/supervisor.d:/etc/supervisor/conf.d
            - ./docker/ap/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ap/php-fpm/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
            - redis:/var/lib/redis
volumes:
    redis:
        driver: local
    mysql:
        driver: local
    minio:
        driver: local
